Extension Documentation Template
================================

== Building docs from the template

You will need the latest version of
http://maven.apache.org/download.html[Maven 3] to build the
documentation.

Simply type:

----
mvn clean install
----

After the build you should find a PDF in +target/docbkx/pdf/+ and a
web version in +target/docbkx/webhelp+.

== Template files

The template source is contained in +src/docbkx/+.  You will find the
following files in the directory.

|===========================================================
|+src/docbkx/acme-temp.xml+  | The docbook template.  This contains a narrative description of the extension.
|+src/docbkx/acme-temp.wadl+ | A WADL describing new REST resources.  This WADL is directly referenced by the docbook text.
|+src/docbkx/figures+        | Example figures used by the template. You can put you custom figures and images here.  Note that figures need to come in two flavors SVG and PNG.
|+src/docbkx/samples+        | Sample XML and JSON payloads referenced in the docbook or WADL.
|===========================================================

== How to use the template

The easist way to use the template is to simply modify the
+src/docbkx/acme-temp.xml+ to describe your extension.  You may, add
WADLs, figures, and samples and reference them as is illustrated in
+src/docbkx/acme-temp.xml+.  You may also added related XML and JSON
schema files in the docbkx directory.

When you're done editing the extension and want to publish you docs
type:

----
mvn clean assembly:assembly
----

This will generate a zip file in +target+ which you can mail to
extensions@openstack.org for publication. 
